"""
SAML 2.0 Service Provider for the Keycloak IAM Lab demo application.

Sits alongside the OIDC flows so the same app acts as a relying party over BOTH
federation protocols. Keycloak is the SAML IdP; this module is the SP.

The IdP signing certificate is generated by Keycloak on first start, so it is not
known at build time — the SP fetches Keycloak's SAML descriptor at runtime and merges
it into the settings. SP request signing is disabled (Keycloak signs responses, the SP
verifies them), which avoids managing an SP keypair in this lab.

Requires the `python3-saml` package, which depends on the native `xmlsec1` library
(installed in the Dockerfile).
"""

import os

from onelogin.saml2.auth import OneLogin_Saml2_Auth
from onelogin.saml2.idp_metadata_parser import OneLogin_Saml2_IdPMetadataParser

KEYCLOAK_INTERNAL_URL = os.getenv("KEYCLOAK_INTERNAL_URL", "http://keycloak:8080")
REALM = os.getenv("KEYCLOAK_REALM", "iam-lab")
APP_HOST = os.getenv("APP_HOST", "http://localhost:8000")

# SP entity ID must equal the SAML client's clientId configured in Keycloak.
SP_ENTITY_ID = "saml-app"
IDP_DESCRIPTOR_URL = f"{KEYCLOAK_INTERNAL_URL}/realms/{REALM}/protocol/saml/descriptor"

_settings_cache: dict | None = None


def _build_settings() -> dict:
    """Assemble python3-saml settings, merging Keycloak's live IdP metadata."""
    global _settings_cache
    if _settings_cache is None:
        idp_data = OneLogin_Saml2_IdPMetadataParser.parse_remote(
            IDP_DESCRIPTOR_URL, validate_cert=False
        )
        settings = {
            "strict": True,
            "debug": False,
            "sp": {
                "entityId": SP_ENTITY_ID,
                "assertionConsumerService": {
                    "url": f"{APP_HOST}/saml/acs",
                    "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
                },
                "singleLogoutService": {
                    "url": f"{APP_HOST}/saml/sls",
                    "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
                },
                "NameIDFormat": "urn:oasis:names:tc:SAML:2.0:nameid-format:transient",
            },
            "security": {
                "authnRequestsSigned": False,
                "wantAssertionsSigned": True,
                "wantMessagesSigned": False,
            },
        }
        # Merge the "idp" section parsed from Keycloak's descriptor.
        settings.update(idp_data)
        _settings_cache = settings
    return _settings_cache


def _prepare_request(host: str, path: str, get_data: dict, post_data: dict) -> dict:
    """Adapt a FastAPI request into the dict python3-saml expects."""
    return {
        "https": "on" if APP_HOST.startswith("https") else "off",
        "http_host": host,
        "script_name": path,
        "get_data": get_data,
        "post_data": post_data,
    }


def _init_auth(req: dict) -> OneLogin_Saml2_Auth:
    return OneLogin_Saml2_Auth(req, _build_settings())


def build_login_redirect(host: str, get_data: dict) -> str:
    """Generate the SAML AuthnRequest and return the IdP redirect URL."""
    req = _prepare_request(host, "/saml/login", get_data, {})
    auth = _init_auth(req)
    return auth.login()


def process_acs(host: str, get_data: dict, post_data: dict) -> dict:
    """Validate the SAML response at the Assertion Consumer Service.

    Returns {"nameid": str, "attributes": dict} on success, or raises ValueError.
    """
    req = _prepare_request(host, "/saml/acs", get_data, post_data)
    auth = _init_auth(req)
    auth.process_response()
    errors = auth.get_errors()
    if errors:
        raise ValueError(f"SAML response errors: {errors} — {auth.get_last_error_reason()}")
    if not auth.is_authenticated():
        raise ValueError("SAML response not authenticated")
    return {"nameid": auth.get_nameid(), "attributes": auth.get_attributes()}


def get_sp_metadata() -> str:
    """Return the SP metadata XML (for registering/inspecting the SP)."""
    settings = OneLogin_Saml2_Auth(
        _prepare_request(APP_HOST, "/saml/metadata", {}, {}), _build_settings()
    ).get_settings()
    metadata = settings.get_sp_metadata()
    errors = settings.validate_metadata(metadata)
    if errors:
        raise ValueError(f"Invalid SP metadata: {errors}")
    return metadata
